version: "3.8"

volumes:
  postgres:
  clickhouse:

networks:
  attractify:
    name: attractify

services:
  postgres:
    image: ghcr.io/inovex/attractify/attractify-postgres
    hostname: postgres
    environment:
      POSTGRES_DB: attractify
      POSTGRES_PASSWORD: attractify
      POSTGRES_USER: attractify
    networks:
      - attractify
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres
        target: /db/data
      - ./server/testdata/fixtures/postgres.sql:/docker-entrypoint-initdb.d/2_fixtures.sql

  clickhouse:
    image: ghcr.io/inovex/attractify/attractify-clickhouse
    hostname: clickhouse
    networks:
      - attractify
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - type: volume
        source: clickhouse
        target: /var/lib/clickhouse/

  server:
    image: ghcr.io/inovex/attractify/attractify-server
    hostname: server
    ports:
      - 8080:8080
    networks:
      - attractify
    depends_on:
      - postgres
      - clickhouse
    restart: always
    volumes:
      - ./server/config.sample.json:/app/config.json

  mariadb:
    image: ghcr.io/inovex/attractify/attractify-usecase-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  sportify:
    depends_on:
      - mariadb
    image: ghcr.io/inovex/attractify/attractify-usecase-frontend
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
