version: "3.8"

volumes:
  postgres:
  clickhouse:

networks:
  attractify:
    name: attractify

services:
  postgres:
    image: ghcr.io/inovex/attractify/attractify-postgres
    hostname: postgres
    environment:
      POSTGRES_DB: attractify
      POSTGRES_PASSWORD: <YOUR_PASSWORD>
      POSTGRES_USER: <YOUR_USER>
    networks:
      - attractify
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres
        target: /db/data
    deploy:
      replicas: 1 #Do not change

  clickhouse:
    image: ghcr.io/inovex/attractify/attractify-clickhouse
    hostname: clickhouse
    networks:
      - attractify
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - type: volume
        source: clickhouse
        target: /var/lib/clickhouse/
    deploy:
      replicas: 1 #Do not change

  server:
    image: ghcr.io/inovex/attractify/attractify-server
    hostname: server
    ports:
      - 8080:8080
    networks:
      - attractify
    depends_on:
      - postgres
      - clickhouse
    restart: always
    volumes:
      - ./server/config.json:/app/config.json
    deploy:
      replicas: 1
