FROM ubuntu
LABEL org.opencontainers.image.source https://github.com/inovex/attractify

# Prerequisites
RUN apt-get update
RUN apt-get install -y cmake 
RUN apt-get install -y git 
RUN apt-get install -y ninja-build
RUN apt-get install -y python
RUN apt-get install -y wget
RUN apt-get install -y lsb-release software-properties-common
RUN apt-get install -y software-properties-common
RUN apt-get install -y curl
RUN curl -o llvm.sh https://apt.llvm.org/llvm.sh
RUN chmod +x llvm.sh
RUN ./llvm.sh
RUN export CC=clang-13
RUN export CXX=clang++-13

# Clone ClickHouse Repo
RUN git clone --recursive https://github.com/ClickHouse/ClickHouse.git

# Install cross-compilation Toolset
RUN cd ClickHouse
RUN mkdir -p build-aarch64/cmake/toolchain/linux-aarch64
RUN wget 'https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz?revision=2e88a73f-d233-4f96-b1f4-d8b36e9bb0b9&la=en' -O gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz
RUN tar xJf gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz -C build-aarch64/cmake/toolchain/linux-aarch64 --strip-components=1

# Build Clickhouse
RUN cd ClickHouse
RUN mkdir build-arm64
RUN CC=clang-13 CXX=clang++-13 cmake . -Bbuild-arm64 -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-aarch64.cmake
RUN ninja -C build-arm64
