name: CI for attractify

on:
  push:
    branches:
      - bhomuth/packages

env:
  REGISTRY: ghcr.io

jobs:
  # build-frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: run build.sh
  #       run: |
  #         ls
  #         cd frontend
  #         yarn
  #         ./build.sh

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: run build.sh
        run: |
          ls
          cd frontend
          yarn
          ./build.sh

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          file: server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/inovex/attractify/attractify-server
    
  # build-postgres:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.BUILD_TOKEN }}

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
        
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build and push server
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: docker/postgres/Dockerfile
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: ghcr.io/inovex/attractify/attractify-postgres