name: CI for attractify

on:
  push:
    branches:
      - bhomuth/packages

env:
  REGISTRY: ghcr.io

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: nodeChacheStep
        uses: actions/cache@v2
        env: 
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os}}-
      
      - name: install yarn dependencies
        if: steps.nodeCacheStep.ouputs.cache-hit != 'true'
        run: |
          cd frontend
          yarn
        
      - name: run build.sh
        run: |
          cd frontend
          ./build.sh

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.BUILD_TOKEN }}

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
        
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build and push server
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: server/Dockerfile
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: ghcr.io/inovex/attractify/attractify-server
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
    
  # build-postgres:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.BUILD_TOKEN }}

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
        
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build and push postgres
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: docker/postgres/Dockerfile
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: ghcr.io/inovex/attractify/attractify-postgres

  # build-clickhouse:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.BUILD_TOKEN }}
            
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
        
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build and push amd64
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: docker/clickhouse/Dockerfile.amd64
  #         platforms: linux/amd64
  #         push: true
  #         tags: ghcr.io/inovex/attractify/attractify-clickhouse:amd64

  #     - name: Build and push arm64
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: docker/clickhouse/Dockerfile.arm64
  #         platforms: linux/arm64
  #         push: true
  #         tags: ghcr.io/inovex/attractify/attractify-clickhouse:arm64
      
  #     - name: Create & push manifest
  #       run: |
  #         docker manifest create ghcr.io/inovex/attractify/attractify-clickhouse ghcr.io/inovex/attractify/attractify-clickhouse:amd64 ghcr.io/inovex/attractify/attractify-clickhouse:arm64
  #         docker manifest push ghcr.io/inovex/attractify/attractify-clickhouse